### ISSUE TITLE
Issues with slider pager and arrows 

### ISSUE THREAD

**Issue by sorina3rev** [a3rev/a3-responsive-slider#2]
@alextuan Hello Tuan. I see a issue with the slider pager and arrows on this site: https://tv.a3de.info/ .
I have add a slider on home page and style the pager and arrows. I can see the arrows on the preview but not on the front end, the pagers can't bee seen.

![screenshot](https://gyazo.com/54e042d6d3fcc2d396b013d92247731f.png)

**Comment by alextuan** [comment]
It's not issue, have explain on slack
